"""
Trains the ROLE model to approximate PCA-reduced fMRI responses from
COCO category label sequences, using frozen BERT filler embeddings.

Modifications from original ROLE (Soulos et al. 2020):
  - Transformer-based role assigner (replaces LSTM)
  - Temperature annealing during training
  - Entropy regularization
  - fMRI responses as target encodings (replaces TPDN encodings)
  - Checkpoint selection via pure val MSE
"""

import sys
import json
import random
import numpy as np
import torch
import torch.nn as nn
from torch.autograd import Variable
from torch import optim
import matplotlib.pyplot as plt
from tqdm import tqdm
import torch.nn.functional as F

from role_learning_tensor_product_encoder import RoleLearningTensorProductEncoder
from sklearn.metrics import r2_score

# --------------------
# Utilities
# --------------------

def set_seed(seed):
    use_cuda = torch.cuda.is_available()
    print(f"CUDA available: {use_cuda}")
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if use_cuda:
        torch.cuda.manual_seed(seed)
        torch.backends.cudnn.deterministic = True
    device = torch.device("cuda" if use_cuda else "cpu")
    return device


def get_temperature(epoch, max_epochs, T_start=5.0, T_end=0.5):
    """Anneal temperature from T_start to T_end over training"""
    progress = epoch / max_epochs
    return T_start * (T_end / T_start) ** progress


def entropy_loss(role_probs):
    """Encourage low-entropy (confident) role assignments

    Args:
        role_probs: (seq_len, batch, n_roles) or (batch, seq_len, n_roles)
    """
    # Add small epsilon for numerical stability
    entropy = -(role_probs * torch.log(role_probs + 1e-10)).sum(dim=-1)
    return entropy.mean()


class RoleLearningInstance(object):
    def __init__(self, filler, target_encoding, target_roles=None):
        self.filler = filler                    # LongTensor [1, seq_len]
        self.target_encoding = target_encoding  # FloatTensor [1, encoding_dim]
        self.target_roles = target_roles        # LongTensor [1, seq_len]


# --------------------
# Data loading
# --------------------

def load_fmri_encodings(metadata_filename, targets_filename, device, expected_dim=None):
    """
    Load PCA-reduced fMRI targets from the files generated by generate_full_fmri.py.

    generate_full_fmri.py writes:
      - fmri_targets_pca16.npy: array of shape (n_images, 16)
      - fmri_metadata_pca16.json: records with filler_ids, role_ids, and fmri_row

    This replaces the older JSON-only loader that expected each record to contain
    a target_encoding field directly.
    """
    print(f"Loading metadata from {metadata_filename}...")
    try:
        with open(metadata_filename, 'r') as f:
            metadata = json.load(f)
    except FileNotFoundError:
        print(f"ERROR: Metadata file {metadata_filename} not found.")
        print("Please run generate_full_fmri.py first.")
        sys.exit(1)

    print(f"Loading PCA fMRI targets from {targets_filename}...")
    try:
        targets = np.load(targets_filename)
    except FileNotFoundError:
        print(f"ERROR: Target file {targets_filename} not found.")
        print("Please run generate_full_fmri.py first.")
        sys.exit(1)

    if not metadata:
        print("ERROR: No metadata records found.")
        sys.exit(1)
    if targets.ndim != 2:
        print(f"ERROR: Expected targets to be 2D, got shape {targets.shape}")
        sys.exit(1)
    if expected_dim is not None and targets.shape[1] != expected_dim:
        print(
            f"ERROR: Expected PCA target dimension {expected_dim}, "
            f"but {targets_filename} has shape {targets.shape}."
        )
        sys.exit(1)

    print(f"Loaded {len(metadata)} metadata records")
    print(f"Loaded target matrix with shape {targets.shape}")

    # Determine role offset (role_ids are usually 0-indexed, but remap for safety)
    all_role_ids = []
    for entry in metadata:
        if entry.get('role_ids') is not None:
            all_role_ids.extend(entry['role_ids'])
    role_offset = min(all_role_ids) if all_role_ids else 0
    print(f"Role offset: {role_offset}")

    data = []
    skipped = 0
    for default_row, entry in enumerate(metadata):
        filler_ids = entry['filler_ids']
        fmri_row = int(entry.get('fmri_row', default_row))
        if fmri_row < 0 or fmri_row >= targets.shape[0]:
            skipped += 1
            continue

        target_encoding = targets[fmri_row]  # PCA-reduced fMRI vector, e.g. 16 dims
        role_ids = entry.get('role_ids', None)

        filler_t = Variable(torch.LongTensor(filler_ids), requires_grad=False).unsqueeze(0)
        encoding_t = Variable(torch.FloatTensor(target_encoding), requires_grad=False).unsqueeze(0)

        if role_ids is not None:
            remapped_role_ids = [r - role_offset for r in role_ids]
            role_t = Variable(torch.LongTensor(remapped_role_ids), requires_grad=False).unsqueeze(0)
        else:
            role_t = None

        filler_t = filler_t.to(device)
        encoding_t = encoding_t.to(device)
        if role_t is not None:
            role_t = role_t.to(device)

        data.append(RoleLearningInstance(filler_t, encoding_t, role_t))

    if not data:
        print("ERROR: No valid ROLE training instances were created.")
        sys.exit(1)

    if skipped:
        print(f"Skipped {skipped} metadata records with invalid fmri_row values")

    print(f"Created {len(data)} instances")
    print(f"  Sequence length:           {len(metadata[0]['filler_ids'])}")
    print(f"  Target encoding dimension: {targets.shape[1]}")
    return data, role_offset


# --------------------
# Training helpers
# --------------------

# --------------------
# Training helpers
# --------------------

def compute_target_stats(data):
    """Compute mean and std over target_encoding features."""
    with torch.no_grad():
        xs = [inst.target_encoding.view(-1).cpu().numpy() for inst in data]
        X = np.stack(xs, axis=0)
        mu = torch.from_numpy(X.mean(axis=0)).float()
        sigma = torch.from_numpy(X.std(axis=0) + 1e-6).float()
    return mu, sigma


def _standardize(x, mu, sigma):
    return (x - mu.to(x.device).unsqueeze(0)) / sigma.to(x.device).unsqueeze(0)


def batchify_with_roles(data, batch_size):
    """Create batches that preserve all instance information."""
    batches = []
    for bi in range(0, len(data), batch_size):
        batch_data = data[bi:min(bi + batch_size, len(data))]
        batches.append(batch_data)
    return batches


# --------------------
# ROLE Training
# --------------------

def train_epoch_role(
        model, train_batches, optimizer, criterion,
        use_regularization=True,
        temperature=1.0,
        entropy_weight=0.01,
        mu=None, sigma=None
):
    """Train ROLE for one epoch to match TPDN encodings."""
    model.train()
    import random
    random.shuffle(train_batches)

    total_loss = 0.0
    total_mse = 0.0
    total_one_hot = 0.0
    total_l2 = 0.0
    total_entropy = 0.0
    num_updates = 0

    for batch in tqdm(train_batches, desc=f"Training ROLE (T={temperature:.2f})"):
        fillers = []
        targets = []

        for inst in batch:
            fillers.append(inst.filler)
            targets.append(inst.target_encoding)

        filler_batch = torch.cat(fillers, dim=0)
        target_batch = torch.cat(targets, dim=0)

        optimizer.zero_grad()

        # Forward - get TPDN encoding from ROLE (without final projection)
        pred, role_predictions = model(filler_batch, None, temperature=temperature)

        # Flatten predictions and targets
        pred_flat = pred.view(pred.size(0), -1)
        targ_flat = target_batch.view(target_batch.size(0), -1)

        # Optionally standardize
        if mu is not None and sigma is not None:
            pred_flat = _standardize(pred_flat, mu, sigma)
            targ_flat = _standardize(targ_flat, mu, sigma)

        # MSE reconstruction loss
        mse_loss = criterion(pred_flat, targ_flat)
        loss = mse_loss

        # Optional regularization
        if use_regularization:
            one_hot_loss, l2_loss, unique_loss = model.get_regularization_loss(role_predictions)
            reg_loss = one_hot_loss + l2_loss + unique_loss
            loss = loss + reg_loss

            total_one_hot += float(one_hot_loss.item())
            total_l2 += float(l2_loss.item())

        # Entropy regularization
        if entropy_weight > 0:
            # Get role probabilities
            role_probs = F.softmax(role_predictions / temperature, dim=-1)
            ent_loss = entropy_weight * entropy_loss(role_probs)
            loss = loss + ent_loss
            total_entropy += float(ent_loss.item())

        # Backward
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        optimizer.step()

        total_loss += float(loss.item())
        total_mse += float(mse_loss.item())
        num_updates += 1

    denom = max(1, num_updates)
    return (
        total_loss / denom,
        total_mse / denom,
        total_one_hot / denom,
        total_l2 / denom,
        total_entropy / denom,
    )


@torch.no_grad()
def evaluate_role(role_model, data, temperature=1.0, mu=None, sigma=None):
    """Evaluate ROLE MSE and R² on dataset."""
    role_model.eval()

    preds = []
    targets = []

    for inst in data:
        pred, _ = role_model(inst.filler, None, temperature=temperature)

        pred = pred.view(pred.size(0), -1)
        targ = inst.target_encoding.view(inst.target_encoding.size(0), -1)

        if mu is not None and sigma is not None:
            pred = _standardize(pred, mu, sigma)
            targ = _standardize(targ, mu, sigma)

        preds.append(pred.cpu().numpy())
        targets.append(targ.cpu().numpy())

    preds = np.concatenate(preds, axis=0)
    targets = np.concatenate(targets, axis=0)

    mse = np.mean((preds - targets) ** 2)

    r2 = r2_score(
        targets,
        preds,
        multioutput="uniform_average"
    )

    return mse, r2


# --------------------
# Role assignment tracking
# --------------------

@torch.no_grad()
def snapshot_role_distributions(role_model, data, device, out_dir="role_plots_fmri",
                                epoch_idx=0, max_items=32, temperature=1.0):
    """Run a fixed mini-batch through ROLE and save role assignment distribution plots.

    Saves:
      - out_dir/role_dist_epoch_XXX.png: heatmap of average P(role | position)

    Returns:
      dict with:
        - entropy: mean role-distribution entropy per sequence position
        - sparsity: mean max role probability per sequence position
    """
    import os
    os.makedirs(out_dir, exist_ok=True)

    n = min(max_items, len(data))
    if n <= 0:
        return {"entropy": [], "sparsity": []}

    fillers = []
    for i in range(n):
        f = data[i].filler
        if f.dim() == 2 and f.size(0) == 1:
            f = f.squeeze(0)
        elif f.dim() != 1:
            f = f.view(-1)
        fillers.append(f)

    filler_batch = torch.stack(fillers, dim=0).to(device)  # (B, S)

    role_model.eval()
    _, role_logits = role_model(filler_batch, None, temperature=temperature)  # commonly (S, B, R)

    # Prefer the post-processed role probabilities stored by the role assigner, if available.
    role_probs = None
    if hasattr(role_model, "role_assigner") and hasattr(role_model.role_assigner, "last_role_probs"):
        role_probs = role_model.role_assigner.last_role_probs

    if role_probs is None:
        # Fallback: softmax over role logits.
        if role_logits.dim() == 3:
            # Convert (S, B, R) to (B, S, R) if needed.
            if role_logits.size(1) == filler_batch.size(0):
                role_logits_bsr = role_logits.transpose(0, 1)
            else:
                role_logits_bsr = role_logits
            role_probs = F.softmax(role_logits_bsr / max(temperature, 1e-8), dim=-1)
        else:
            raise RuntimeError(f"Unexpected role_logits shape: {tuple(role_logits.shape)}")

    # Ensure shape is (B, S, R).
    if role_probs.dim() != 3:
        raise RuntimeError(f"Unexpected role_probs shape: {tuple(role_probs.shape)}")
    if role_probs.size(0) != filler_batch.size(0) and role_probs.size(1) == filler_batch.size(0):
        role_probs = role_probs.transpose(0, 1)

    role_dist = role_probs.mean(dim=0).detach().cpu().numpy()  # (S, R)
    S, R = role_dist.shape

    plt.figure(figsize=(10, 6))
    plt.imshow(role_dist, aspect="auto", cmap="viridis", vmin=0.0, vmax=max(1e-6, role_dist.max()))
    plt.colorbar(label="P(role | position)")
    plt.xlabel("Role index")
    plt.ylabel("Position in sequence")
    plt.title(f"ROLE assignment distribution | epoch {epoch_idx + 1}")
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, f"role_dist_epoch_{epoch_idx + 1:03d}.png"), dpi=200)
    plt.close()

    summaries = {"entropy": [], "sparsity": []}
    for s_idx in range(S):
        p = np.clip(role_dist[s_idx], 1e-12, 1.0)
        summaries["entropy"].append(float(-np.sum(p * np.log(p))))
        summaries["sparsity"].append(float(np.max(p)))

    return summaries


def plot_role_summaries(role_entropy_hist, role_sparsity_hist, role_epochs=None, out_dir="role_plots_fmri"):
    """Plot role-distribution entropy and sparsity over training."""
    import os
    os.makedirs(out_dir, exist_ok=True)

    role_entropy_hist = np.asarray(role_entropy_hist, dtype=float)
    role_sparsity_hist = np.asarray(role_sparsity_hist, dtype=float)

    if role_entropy_hist.size == 0 or role_sparsity_hist.size == 0:
        print("No role-distribution snapshots to plot.")
        return

    if role_epochs is None:
        role_epochs = np.arange(1, role_entropy_hist.shape[0] + 1)
    else:
        role_epochs = np.asarray(role_epochs)

    mean_entropy = np.nanmean(role_entropy_hist, axis=1)
    mean_sparsity = np.nanmean(role_sparsity_hist, axis=1)

    plt.figure(figsize=(10, 6))
    plt.plot(role_epochs, mean_entropy, marker="o", label="Mean entropy")
    plt.xlabel("Epoch")
    plt.ylabel("Entropy")
    plt.title("ROLE assignment entropy across training")
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "role_entropy_over_epochs.png"), dpi=200)
    plt.close()

    plt.figure(figsize=(10, 6))
    plt.plot(role_epochs, mean_sparsity, marker="o", label="Mean max probability")
    plt.xlabel("Epoch")
    plt.ylabel("Max role probability")
    plt.title("ROLE assignment sparsity across training")
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "role_sparsity_over_epochs.png"), dpi=200)
    plt.close()

def plot_training_curves(role_train_mse, role_val_mse,
                         role_train_r2, role_val_r2,
                         role_train_one_hot=None,
                         role_train_l2=None, role_train_entropy=None):
    """Plot training curves."""
    epochs_role = np.arange(1, len(role_train_mse) + 1)

    # ROLE MSE
    plt.figure()
    plt.plot(epochs_role, role_train_mse, marker="o", label="Train MSE")
    plt.plot(epochs_role, role_val_mse, marker="s", label="Val MSE")
    plt.xlabel("Epoch")
    plt.ylabel("MSE")
    plt.title("ROLE Model Reconstruction MSE (fMRI Encodings)")
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig("role_mse_fmri_pca8_updated_arch_unique.png", dpi=200)
    plt.close()
    # ROLE R²
    plt.figure()
    plt.plot(epochs_role, role_train_r2, marker="o", label="Train R²")
    plt.plot(epochs_role, role_val_r2, marker="s", label="Val R²")
    plt.xlabel("Epoch")
    plt.ylabel("R²")
    plt.title("ROLE Model Variance Explained (fMRI Encodings)")
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig("role_r2_fmri_pca8_unique.png", dpi=200)
    plt.close()

    # ROLE Regularization losses
    if role_train_one_hot is not None and role_train_l2 is not None:
        plt.figure()

        eps = 1e-12
        one_hot = np.array(role_train_one_hot, dtype=float)
        l2 = np.array(role_train_l2, dtype=float)

        plt.plot(epochs_role, one_hot + eps, marker="o", label="One-hot reg")
        plt.plot(epochs_role, l2 + eps, marker="^", label="L2 reg")

        if role_train_entropy is not None:
            entropy = np.array(role_train_entropy, dtype=float)
            plt.plot(epochs_role, entropy + eps, marker="d", label="Entropy reg")

        plt.yscale("symlog", linthresh=1e-6)
        plt.xlabel("Epoch")
        plt.ylabel("Loss (symlog)")
        plt.title("ROLE Model – Regularization losses (train)")
        plt.grid(True, linestyle="--", alpha=0.5)
        plt.legend()
        plt.tight_layout()
        plt.savefig("role_model_reg_losses_fmri_pca16.png", dpi=200)
        plt.close()


# --------------------
# Main
# --------------------

def main():
    print("=" * 80)
    print("ROLE APPROXIMATION WITH PCA-16 fMRI ENCODINGS")
    print("=" * 80)

    # =========================
    # Config
    # =========================
    FMRI_METADATA_JSON = "fmri_metadata_pca8.json"
    FMRI_TARGETS_NPY = "fmri_targets_pca8.npy"
    TARGET_ENCODING_DIM = 8
    SEED = 42

    # ROLE training (from scratch)
    TOTAL_ROLE_EPOCHS = 20
    BATCH_SIZE = 4              # reduced from 16 to lower GPU memory usage
    ROLE_LR = 1e-4
    USE_ROLE_REG = True
    STANDARDIZE = True

    # Runtime: validate less frequently
    EVAL_INTERVAL = 5  # validate every N epochs (plus first eval epoch and last)

    # Temperature annealing
    T_START = 5.0
    T_END = 0.5

    # Entropy regularizationm
    ENTROPY_WEIGHT = 0.001

    # Model architecture
    FILLER_DIM = 128    # post-squeeze binding dimension (BERT 768 -> 64 via embedder_squeeze)
    ROLE_DIM = 10       # dense learned role embedding dim (independent of n_roles=80)
    N_ROLES = 10       # total number of possible category positions play around with
    HIDDEN_DIM = 768   # reduced from 768 to lower GPU memory usage
    NUM_LAYERS = 6     # reduced from 4 to lower GPU memory usage
    N_HEAD = 12
    DROPOUT = 0.1

    # Sequence length cap: sequences longer than this are discarded.
    # Transformer attention memory scales as O(S^2), so capping sequence length
    # is the most impactful way to reduce memory. Set to N_ROLES (80) to keep all.
    MAX_SEQ_LEN = 15

    # Role assignment distribution tracking
    PLOT_ROLE_DISTS = True
    ROLE_OUT_DIR = "role_plots_fmri_pca8_unique"
    ROLE_PLOT_EVERY = 5  # snapshot every N epochs
    ROLE_SAMPLE_SIZE = 8

    # =========================
    # Setup
    # =========================
    device = set_seed(SEED)

    # =========================
    # Load data
    # =========================
    print("\n" + "=" * 80)
    print("LOADING DATA")
    print("=" * 80)
    data, role_offset = load_fmri_encodings(
        FMRI_METADATA_JSON,
        FMRI_TARGETS_NPY,
        device,
        expected_dim=TARGET_ENCODING_DIM,
    )

    # Filter to sequences at or below MAX_SEQ_LEN real (non-PAD) tokens.
    # filler_ids[0] is the PAD index (0), so real length = number of non-zero filler ids.
    if MAX_SEQ_LEN < N_ROLES:
        before = len(data)
        data = [inst for inst in data if int((inst.filler != 0).sum()) <= MAX_SEQ_LEN]
        print(f"Filtered sequences to max real length {MAX_SEQ_LEN}: "
              f"{before} -> {len(data)} ({before - len(data)} discarded)")

    seq_len = data[0].filler.size(1)
    encoding_dim = data[0].target_encoding.view(-1).numel()
    num_fillers = max(int(inst.filler.max().item()) for inst in data) + 1

    # n_roles is fixed to N_ROLES (80) regardless of sequence length filter,
    # since the role space covers all 80 possible category positions
    n_roles = N_ROLES

    print(f"\nDataset info:")
    print(f"  Sequences: {len(data)}")
    print(f"  Padded sequence length: {seq_len}")
    print(f"  Max real sequence length: {MAX_SEQ_LEN}")
    print(f"  Num fillers: {num_fillers}")
    print(f"  Num roles: {n_roles}")
    print(f"  Target encoding dimension: {encoding_dim}")
    print(f"  TPR dim (filler_dim * role_dim): {FILLER_DIM * ROLE_DIM}")

    # Compute statistics for standardization
    enc_mu, enc_sigma = compute_target_stats(data) if STANDARDIZE else (None, None)
    if STANDARDIZE:
        print(f"  Encoding mean: {enc_mu.mean().item():.4f}")
        print(f"  Encoding std: {enc_sigma.mean().item():.4f}")

    train_set = data[: int(0.8 * len(data))]
    test_set = data[int(0.8 * len(data)):]
    print(f"\nTrain: {len(train_set)}, Test: {len(test_set)}")

    train_batches = batchify_with_roles(train_set, BATCH_SIZE)

    # =========================
    # Load pretrained BERT filler embeddings
    # =========================
    BERT_EMBEDDING_PATH = "bert_embedding_matrix.pt"
    print(f"\nLoading BERT embedding matrix from {BERT_EMBEDDING_PATH}...")
    try:
        pretrained_filler_embeddings = torch.load(BERT_EMBEDDING_PATH, map_location=device)
        print(f"  Loaded embedding matrix: {pretrained_filler_embeddings.shape}")
    except FileNotFoundError:
        print(f"ERROR: {BERT_EMBEDDING_PATH} not found. Run generate_bert_embeddings.py first.")
        sys.exit(1)

    # =========================
    # Create ROLE model
    # =========================
    print("\n" + "=" * 80)
    print("CREATING ROLE MODEL")
    print("=" * 80)

    role_model = RoleLearningTensorProductEncoder(
        n_roles=n_roles,
        n_fillers=num_fillers,
        filler_dim=FILLER_DIM,
        role_dim=ROLE_DIM,
        final_layer_width=TARGET_ENCODING_DIM,  # projects ROLE output -> 16-dim PCA fMRI target
        binder="tpr",
        role_learner_hidden_dim=HIDDEN_DIM,
        num_layers=NUM_LAYERS,
        nhead=N_HEAD,
        dim_feedforward=4 * HIDDEN_DIM,
        dropout=DROPOUT,
        softmax_roles=True,
        embedder_squeeze=64,                    # squeezes BERT 768-dim -> 64-dim before binding
        unique_role_regularization_weight=0.1,  # disabled: not meaningful for dense role embeddings
        pretrained_filler_embeddings=pretrained_filler_embeddings,
    ).to(device)
    role_model.use_regularization(USE_ROLE_REG)

    # =========================
    # Training from scratch setup
    # =========================
    start_epoch_0idx = 0
    total_role_epochs = TOTAL_ROLE_EPOCHS
    print(f"\nROLE training plan:")
    print(f"  Training from scratch for {total_role_epochs} epochs")
    print(f"  Temperature annealing: {T_START} → {T_END}")
    print(f"  Entropy regularization weight: {ENTROPY_WEIGHT}")
    print(f"  Validation interval: every {EVAL_INTERVAL} epochs")
    print(f"  Checkpoint selection: pure val MSE")

    # =========================
    # Train ROLE (resume)
    # =========================
    print("\n" + "=" * 80)
    print("TRAINING ROLE MODEL")
    print("=" * 80)

    role_optimizer = optim.Adam(role_model.parameters(), lr=ROLE_LR)
    role_criterion = nn.MSELoss()

    # Histories (only for the new/resumed segment)
    role_train_mse_hist = []
    role_train_one_hot_hist = []
    role_train_l2_hist = []
    role_train_entropy_hist = []
    role_val_mse_hist = []
    role_train_r2_hist = []
    role_val_r2_hist = []

    role_entropy_hist = []
    role_sparsity_hist = []
    role_snapshot_epochs = []

    best_role_path = "best_role_model_fmri_pca16.pt"
    best_score = float("inf")
    best_role_epoch_1idx = None
    best_role_mse = float("inf")

    for epoch_0idx in range(start_epoch_0idx, total_role_epochs):
        temperature = get_temperature(epoch_0idx, total_role_epochs, T_START, T_END)

        _, avg_mse, avg_one_hot, avg_l2, avg_entropy = train_epoch_role(
            role_model,
            train_batches,
            role_optimizer,
            role_criterion,
            use_regularization=USE_ROLE_REG,
            temperature=temperature,
            entropy_weight=ENTROPY_WEIGHT,
            mu=enc_mu,
            sigma=enc_sigma
        )

        role_train_mse_hist.append(avg_mse)
        role_train_one_hot_hist.append(avg_one_hot)
        role_train_l2_hist.append(avg_l2)
        role_train_entropy_hist.append(avg_entropy)

        # Evaluate less frequently
        epoch_1idx = epoch_0idx + 1
        do_eval = (epoch_1idx == (start_epoch_0idx + 1)) or (epoch_1idx == total_role_epochs) or (epoch_1idx % EVAL_INTERVAL == 0)

        if do_eval:
            train_eval_mse, train_r2 = evaluate_role(role_model, train_set, temperature=temperature, mu=enc_mu, sigma=enc_sigma)
            val_mse, val_r2 = evaluate_role(role_model, test_set, temperature=temperature, mu=enc_mu, sigma=enc_sigma)

            # Checkpoint selection: pure val MSE
            if val_mse < best_score:
                best_score = float(val_mse)
                best_role_epoch_1idx = epoch_1idx
                best_role_mse = float(val_mse)
                torch.save(role_model.state_dict(), best_role_path)
                print(
                    f"  ✓ Saved best ROLE model: {best_role_path} "
                    f"(epoch={best_role_epoch_1idx}, mse={best_role_mse:.6f})"
                )

            print(
                f"Epoch {epoch_1idx}/{total_role_epochs} (T={temperature:.3f}): "
                f"Train MSE={avg_mse:.6f}, Val MSE={val_mse:.6f}, "
                f"Train R²={train_r2:.6f}, Val R²={val_r2:.6f}, "
                f"Entropy={avg_entropy:.6f}"
            )

            role_val_mse_hist.append(val_mse)
            role_train_r2_hist.append(train_r2)
            role_val_r2_hist.append(val_r2)
        else:
            print(
                f"Epoch {epoch_1idx}/{total_role_epochs} (T={temperature:.3f}): "
                f"Train MSE={avg_mse:.6f}, (skipping val; interval={EVAL_INTERVAL}) "
                f"Entropy={avg_entropy:.6f}"
            )
            role_val_mse_hist.append(float("nan"))
            role_train_r2_hist.append(float("nan"))
            role_val_r2_hist.append(float("nan"))

        if PLOT_ROLE_DISTS and (epoch_1idx == 1 or epoch_1idx == total_role_epochs or epoch_1idx % ROLE_PLOT_EVERY == 0):
            summaries = snapshot_role_distributions(
                role_model, test_set, device,
                out_dir=ROLE_OUT_DIR,
                epoch_idx=epoch_0idx,
                max_items=ROLE_SAMPLE_SIZE,
                temperature=temperature,
            )
            role_entropy_hist.append(summaries["entropy"])
            role_sparsity_hist.append(summaries["sparsity"])
            role_snapshot_epochs.append(epoch_1idx)

    # Load best ROLE model before decoder training / substitution eval
    try:
        role_model.load_state_dict(torch.load(best_role_path, map_location=device))
        print(f"\nLoaded best ROLE model from {best_role_path}")
        if best_role_epoch_1idx is not None:
            print(f"  Best epoch: {best_role_epoch_1idx} | mse={best_role_mse:.6f}")
    except FileNotFoundError:
        print(f"\nWARNING: Best ROLE checkpoint not found at {best_role_path}. Using current in-memory model.")

    # Plot training curves
    plot_training_curves(
        role_train_mse_hist,
        role_val_mse_hist,
        role_train_r2_hist,
        role_val_r2_hist,
        role_train_one_hot=role_train_one_hot_hist,
        role_train_l2=role_train_l2_hist,
        role_train_entropy=role_train_entropy_hist,
    )

    if PLOT_ROLE_DISTS and role_entropy_hist:
        plot_role_summaries(
            role_entropy_hist,
            role_sparsity_hist,
            role_epochs=role_snapshot_epochs,
            out_dir=ROLE_OUT_DIR,
        )
        print(f"Saved role assignment distribution plots to: {ROLE_OUT_DIR}")

    print("\n" + "=" * 80)
    print("TRAINING COMPLETE!")
    print("=" * 80)
    print(f"\nFinal Results:")
    print(f"  ROLE Model:")
    if best_role_epoch_1idx is not None:
        print(f"    Best epoch:    {best_role_epoch_1idx}")
        print(f"    Best val MSE:  {best_role_mse:.6f}")
    else:
        print(f"    Best checkpoint info: N/A")
    print(f"\nRole offset applied: {role_offset}")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print("\n" + "=" * 80)
        print("ERROR OCCURRED!")
        print("=" * 80)
        print(f"Error type: {type(e).__name__}")
        print(f"Error message: {str(e)}")
        print("\nFull traceback:")
        import traceback

        traceback.print_exc()
        print("\n" + "=" * 80)
        sys.exit(1)
